server:
  port: 8080

spring:
  application:
    name: eureka-zone1

eureka:
#  server:
#    renewalPercentThreshold: 0.49
#  server:
#    enableSelfPreservation: true
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/